# nginx proxy address - http://172.17.0.1:5572

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  rclone:
    image: rclone/rclone:latest
    container_name: rclone-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - rclone
    ports:
      - "5572:5572"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./volumes/config/rclone:/config
      - ./volumes/data/rclone:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5572"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  rclone:
    external: false
